Modularize validation + parsing

diff --git a/timemachine b/timemachine
--- a/timemachine
+++ b/timemachine
@@ -16,7 +16,7 @@ MY_VERS="0.3"
 MY_DATE="2018-12-22"
 
 # cmd [-r] <src> <dst> [rsync opts]
-verbose=    # -v Verbose output
+verbose=   # -v Verbose output
 
 
 
@@ -87,78 +87,76 @@ logerr() {
 ################################################################################
 # Entrypoint: Parse cmd args
 ################################################################################
-
-# Parse input args with getopts
-while getopts :vhV-: opt; do
-	# ----- long options
-	if [ "$opt" = "-" ]; then
-		opt=$OPTARG
-		[ -z "$opt" ] && break	# "--" terminates argument processing
-	fi
-	# shellcheck disable=SC2214
-	case $opt in
-		# ---- Help / version
-		V | version)
-			print_version
-			exit
-			;;
-		h | help)
-			print_usage
-			exit
-			;;
-		# ----- Options
-		v | verbose)
-			verbose="verbose"
-			;;
-		\?)	logerr "Unknown option -$OPTARG, see -h for help."
-			exit 2
-			;;
-		*)	logerr "Unknown option --$opt, see -h for help."
-			exit 2
-			;;
-	esac
-done
-shift $((OPTIND-1))		# remove parsed options and args from $@ list
+parse_args() {
+	# Parse input args with getopts
+	while getopts :vhV-: opt; do
+		# ----- long options
+		if [ "$opt" = "-" ]; then
+			opt=$OPTARG
+			[ -z "$opt" ] && break	# "--" terminates argument processing
+		fi
+		# shellcheck disable=SC2214
+		case $opt in
+			# ---- Help / version
+			V | version)
+				print_version
+				exit
+				;;
+			h | help)
+				print_usage
+				exit
+				;;
+			# ----- Options
+			v | verbose)
+				verbose="verbose"
+				;;
+			\?)	logerr "Unknown option -$OPTARG, see -h for help."
+				exit 2
+				;;
+			*)	logerr "Unknown option --$opt, see -h for help."
+				exit 2
+				;;
+		esac
+	done
+	shift $((OPTIND-1))		# remove parsed options and args from $@ list
+}
 
 
 ################################################################################
 # Entrypoint: Validate cmd args
 ################################################################################
+validate_args() {
+	# Check arg count
+	[ "${#}" -lt "2" ] && logerr "<source> and <destination> are required. See -h for help." && exit 1
 
-if [ "${#}" -lt "2" ]; then
-	logerr "<source> and <destination> are required. See -h for help."
-	exit 1
-fi
+	# Source validity
+	[ ! -d "${1}" ] && [ ! -f "${1}" ] && logerr "Source directory does not exist. See -h for help." && exit 1
 
-if [ ! -d "${1}" ] && [ ! -f "${1}" ]; then
-	logerr "Source directory does not exist. See -h for help."
-	exit 1
-fi
-
-if [ ! -d "${2}" ] && [ ! -f "${2}" ]; then
-	echo "Target directory does not exist.\n"
-	read -r -p  "Would you like to create a new one?[y/n] " response
-	if [[ "${response}" =~ ^([yY][eE][sS]|[yY])+$ ]]
-	then
-		mkdir "${2}"
-	else
-		logerr "Target directory does not exist. See -h for help."
-		echo "Quitting ..."
-		exit 1
+	# Target directory check
+	if [ ! -d "${2}" ] && [ ! -f "${2}" ]; then
+		echo "Target directory does not exist.\n"
+		read -r -p  "Would you like to create a new one?[y/n] " response
+		if [[ "${response}" =~ ^([yY][eE][sS]|[yY])+$ ]]
+		then
+			mkdir "${2}"
+		else
+			logerr "Target directory does not exist. See -h for help." && exit 1
+		fi
 	fi
-fi
 
-if ! command -v rsync >/dev/null 2>&1; then
-	logerr "rsync binary not found but required."
-	exit 1
-fi
+	# Check for rsync binary
+	if ! command -v rsync >/dev/null 2>&1; then
+		logerr "rsync binary not found but required." && exit 1
+	fi
+}
 
 
 
 ################################################################################
 # Main Entrypoint
 ################################################################################
-
+parse_args "${@}"
+validate_args "${@}"
 # Get arguments and remove them afterwards to have ${@} contain
 # all additional rsync options
 SRC="${1}"
